name: Python application

on:
  push:
    branches: [ main ]  # Trigger workflow on push to main branch
  pull_request:
    branches: [ main ]  # Trigger workflow on pull requests to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4 

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11' 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip  # Upgrade pip to latest version
        pip install -r requirements.txt      # Install dependencies from requirements.txt

    - name: Run your tests or scripts
      run: |
        python3 application_evaluator.py   # Uncomment to run your main application
        # pytest                           # Uncomment if you want to run tests
  
